CREATE SCHEMA ecommerce;
-- DROP SCHEMA ecommerce;
USE ecommerce;

CREATE TABLE Cliente (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Produto (
  id INT AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(255) NOT NULL UNIQUE,
  descricao TEXT NOT NULL,
  preco DECIMAL(10,2) NOT NULL,
  categoria VARCHAR(255) NOT NULL,
  imagemUrl VARCHAR(500),
  estoque INT NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  avaliacao DECIMAL(2,1) DEFAULT 0.0
);

CREATE TABLE Pedido (
  id INT AUTO_INCREMENT PRIMARY KEY,
  clienteId INT NOT NULL,
  total DECIMAL(10,2) NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (clienteId) REFERENCES Cliente(id)
);

CREATE TABLE ItemPedido (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pedidoId INT NOT NULL,
  produtoId INT NOT NULL,
  quantidade INT NOT NULL,
  FOREIGN KEY (pedidoId) REFERENCES Pedido(id) ON DELETE CASCADE,
  FOREIGN KEY (produtoId) REFERENCES Produto(id)
);
